import React from 'react';
import { CompanyLogo } from '../common/CompanyLogo';

export const PrivacyPolicy = () => {
  return (
    <div className="public-page privacy-policy-page">
      <header className="public-header">
        <div className="public-container">
          <CompanyLogo className="public-logo" />
        </div>
      </header>
      <main className="public-content">
        <div className="public-container">
          <h1>Privacy Policy</h1>
          <p className="last-updated">Last updated: August 13, 2026</p>

          <section>
            <h2>Introduction</h2>
            <p>
              Welcome to <strong>KAISER WHALE Marketing</strong>, an application provided by <strong>Whale Enterprise Pvt. Ltd.</strong> ("we", "us", or "our"). We are committed to protecting the privacy and security of your information. This Privacy Policy explains how we collect, use, and safeguard data within the KAISER WHALE Marketing application.
            </p>
            <p>
              This application is a business tool designed for the employees and authorized personnel of Whale Enterprise Pvt. Ltd. to manage marketing visits, reporting, and operational workflows.
            </p>
          </section>

          <section>
            <h2>1. Information We Collect</h2>
            <ul>
              <li><strong>Account and Login Information:</strong> We collect your professional email address and password to provide secure access to the application. Authentication is managed through Supabase.</li>
              <li><strong>Employee Profile Information:</strong> We store profile details including your full name, employee ID, mobile number, role, designation, and department.</li>
              <li><strong>Marketing Visit Information:</strong> Authorized users enter information regarding marketing visits, including customer or organization names, contact persons, and visit purposes.</li>
              <li><strong>Schedules and Reports:</strong> The application collects and stores visit plans, schedules, visit reports, and daily summary reports generated by users.</li>
              <li><strong>Operational Data:</strong> We collect follow-up information, activity logs, and director comments relevant to business operations.</li>
              <li><strong>Device Information:</strong> We may collect basic device information necessary for delivering internal application notifications and ensuring application security.</li>
            </ul>
          </section>

          <section>
            <h2>2. How Information Is Used</h2>
            <p>We use the collected information for the following purposes:</p>
            <ul>
              <li>Secure authentication and access control.</li>
              <li>Management of marketing visits and employee schedules.</li>
              <li>Business reporting and performance analysis.</li>
              <li>Facilitating internal communication and feedback (e.g., Director comments).</li>
              <li>Delivering relevant internal notifications.</li>
              <li>Application administration, security, and troubleshooting.</li>
            </ul>
          </section>

          <section>
            <h2>3. Data Storage and Security</h2>
            <p>
              The data collected by the application is stored securely using Supabase cloud infrastructure. We implement reasonable technical and organizational measures designed to protect your information from unauthorized access, disclosure, or misuse. Access to data is restricted based on user roles (Marketing, Director, Admin).
            </p>
          </section>

          <section>
            <h2>4. Data Sharing</h2>
            <p>
              Information collected within this application is intended for internal business use by <strong>Whale Enterprise Pvt. Ltd.</strong> We do not sell your personal information to third parties. Information may be accessible to service providers (such as Supabase) solely for the purpose of maintaining application functionality.
            </p>
          </section>

          <section>
            <h2>5. Location Data</h2>
            <p>
              The current version of the KAISER WHALE Marketing application <strong>does not collect precise location information</strong> (GPS data) from your device.
            </p>
          </section>

          <section>
            <h2>6. Notifications</h2>
            <p>
              The application uses internal notifications to alert users about plan approvals, feedback, and operational updates. These notifications are delivered within the app environment.
            </p>
          </section>

          <section>
            <h2>7. Data Retention and Deletion</h2>
            <p>
              We retain business-related information as long as necessary to fulfill the operational requirements of Whale Enterprise Pvt. Ltd. or as required by law. Users may request the correction or deletion of their personal profile information through their organization's administrator.
            </p>
          </section>

          <section>
            <h2>8. Children's Privacy</h2>
            <p>
              KAISER WHALE Marketing is a professional workforce application and is not intended for use by children under the age of 18. We do not knowingly collect information from children.
            </p>
          </section>

          <section>
            <h2>9. Changes to This Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
            </p>
          </section>

          <section>
            <h2>10. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us at:</p>
            <p>
              <strong>Whale Enterprise Pvt. Ltd.</strong><br />
              Email: <a href="mailto:weplcbe@gmail.com" className="public-link">weplcbe@gmail.com</a>
            </p>
          </section>
        </div>
      </main>
      <footer className="public-footer">
        <div className="public-container">
          <p>&copy; 2026 Whale Enterprise Pvt. Ltd. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default PrivacyPolicy;
