import React, { useMemo, useState } from 'react';
import { MessageSquare, Search } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Badge, Button, DataTable, EmptyState, FormField, Modal, PageHeader, SelectField, TextArea } from '../ui';

export const CommentsHistory = () => {
  const { directorComments, users, addDirectorComment, refreshEntity, lastUpdated } = useApp(); const [search, setSearch] = useState(''); const [module, setModule] = useState('All'); const [selected, setSelected] = useState(null); const [newComment, setNewComment] = useState(false); const [message, setMessage] = useState(''); const [employeeId, setEmployeeId] = useState('');
  const comments = useMemo(() => directorComments.filter((item) => module === 'All' || item.targetModule === module).filter((item) => `${item.message || item.comment || ''} ${item.targetEmployeeName || ''} ${item.targetModule || ''}`.toLowerCase().includes(search.toLowerCase())), [directorComments, module, search]);
  const marketing = users.filter((user) => ['Marketing', 'Marketing Team'].includes(user.role));
  const modules = [...new Set(directorComments.map((item) => item.targetModule).filter(Boolean))];
  const submit = async (event) => { event.preventDefault(); const employee = marketing.find((item) => item.employeeId === employeeId); if (!employee || !message.trim()) return; await addDirectorComment({ targetEmployeeId: employee.employeeId, targetEmployeeName: employee.fullName || employee.employeeName, targetModule: 'General', referenceId: null, message }); setMessage(''); setNewComment(false); };
  const columns = [{ key: 'type', label: 'Module', render: (row) => <Badge>{row.targetModule || row.commentType || 'General'}</Badge> }, { key: 'comment', label: 'Comment', render: (row) => row.message || row.comment || 'Not provided' }, { key: 'related', label: 'Related Record', render: (row) => row.referenceId || 'Not provided' }, { key: 'employee', label: 'Employee', render: (row) => row.targetEmployeeName || row.targetEmployeeId || 'Not provided' }, { key: 'date', label: 'Created', render: (row) => row.createdAt ? new Date(row.createdAt).toLocaleString() : 'Not provided' }, { key: 'read', label: 'Read', render: (row) => <Badge tone={row.isRead ? 'success' : 'warning'}>{row.isRead ? 'Read' : 'Unread'}</Badge> }, { key: 'action', label: 'Action', render: (row) => <Button variant="secondary" onClick={() => setSelected(row)}>View Reply</Button> }];
  return <div className="ds-page"><PageHeader title="Comments History" description={`Director guidance and Marketing replies. Last updated ${lastUpdated ? lastUpdated.toLocaleTimeString() : 'Not available'}.`} actions={<Button onClick={() => setNewComment(true)}>Add Comment</Button>} /><div className="director-filter-bar"><div className="director-search"><Search size={17} /><FormField label="Search comments" value={search} onChange={(event) => setSearch(event.target.value)} /></div><SelectField label="Module" value={module} onChange={(event) => setModule(event.target.value)}><option>All</option>{modules.map((item) => <option key={item}>{item}</option>)}</SelectField></div><DataTable rows={comments} columns={columns} empty={<EmptyState icon={MessageSquare} title="No Director comments found" description="Clear filters, refresh, or add guidance for a Marketing employee." action={<Button onClick={() => refreshEntity('director_comments')}>Refresh</Button>} />} /><Modal open={Boolean(selected)} onClose={() => setSelected(null)} title="Comment Details" subtitle={selected?.targetModule || 'General'} footer={<Button variant="secondary" onClick={() => setSelected(null)}>Close</Button>}>{selected && <div className="director-detail-grid"><div><small>Comment</small><strong>{selected.message || selected.comment || 'Not provided'}</strong></div><div><small>Replies</small><strong>{selected.replies?.length ? selected.replies.map((reply) => reply.message || reply).join(' · ') : 'No reply received'}</strong></div></div>}</Modal><Modal open={newComment} onClose={() => setNewComment(false)} title="Add Director Comment" footer={<><Button variant="secondary" onClick={() => setNewComment(false)}>Cancel</Button><Button type="submit" form="director-comment-form">Send Comment</Button></>}><form id="director-comment-form" onSubmit={submit} className="ds-form-grid"><SelectField className="ds-field--full" label="Marketing Employee" required value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">Select employee</option>{marketing.map((employee) => <option key={employee.id} value={employee.employeeId}>{employee.fullName || employee.employeeName}</option>)}</SelectField><TextArea className="ds-field--full" label="Comment" required value={message} onChange={(event) => setMessage(event.target.value)} /></form></Modal></div>;
};
export default CommentsHistory;
