import React, { useMemo, useState } from 'react';
import { Building2, Search } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Badge, Button, DataTable, EmptyState, FormField, Modal, PageHeader, SelectField, TextArea } from '../ui';

export const CustomersOverview = () => {
  const { customers, visitPlans, followUps, tenders, directorComments, addDirectorComment, refreshEntity, lastUpdated } = useApp();
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [selected, setSelected] = useState(null); const [commentTarget, setCommentTarget] = useState(null); const [comment, setComment] = useState('');
  const rows = useMemo(() => customers.filter((item) => status === 'All' || item.status === status).filter((item) => `${item.organizationName || ''} ${item.district || ''} ${item.contactPerson || ''}`.toLowerCase().includes(search.toLowerCase())), [customers, search, status]);
  const postComment = async () => { if (!comment.trim()) return; await addDirectorComment({ targetEmployeeId: commentTarget.createdBy, targetEmployeeName: commentTarget.createdByName || commentTarget.createdBy, targetModule: 'Customer', referenceId: commentTarget.id, message: comment.trim() }); setComment(''); setCommentTarget(null); };
  const columns = [{ key: 'organizationName', label: 'Organization', render: (row) => <><strong>{row.organizationName || 'Not provided'}</strong><small>{row.organizationType || 'Not provided'}</small></> }, { key: 'location', label: 'Location', render: (row) => `${row.city || 'Not provided'}, ${row.district || 'Not provided'}` }, { key: 'contact', label: 'Contact', render: (row) => <>{row.contactPerson || 'Not provided'}<small>{row.mobile || row.mobileNumber || 'Not provided'}</small></> }, { key: 'products', label: 'Products', render: (row) => (row.interestedProducts || row.products || []).join?.(', ') || 'Not provided' }, { key: 'status', label: 'Approval', render: (row) => <Badge tone={row.status === 'Approved' ? 'success' : 'warning'}>{row.status || 'Pending'}</Badge> }, { key: 'action', label: 'Actions', render: (row) => <div className="ds-page-actions"><Button variant="secondary" onClick={() => setSelected(row)}>View</Button><Button variant="secondary" onClick={() => setCommentTarget(row)}>Comment</Button></div> }];
  return <div className="ds-page"><PageHeader title="Customers Overview" description={`Read-only customer activity across the Marketing team. Last updated ${lastUpdated ? lastUpdated.toLocaleTimeString() : 'Not available'}.`} /><div className="director-filter-bar"><div className="director-search"><Search size={17} /><FormField label="Search customers" value={search} onChange={(event) => setSearch(event.target.value)} /></div><SelectField label="Approval Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Pending</option><option>Approved</option><option>Rejected</option></SelectField></div><DataTable rows={rows} columns={columns} empty={<EmptyState icon={Building2} title="No customers match these filters" description="Clear filters or refresh customer data." action={<><Button variant="secondary" onClick={() => { setSearch(''); setStatus('All'); }}>Clear Filters</Button><Button onClick={() => refreshEntity('customers')}>Refresh</Button></>} />} /><Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.organizationName || 'Customer Details'} subtitle={`${selected?.organizationType || 'Not provided'} · ${selected?.city || 'Not provided'}`} footer={<Button variant="secondary" onClick={() => setSelected(null)}>Close</Button>}>{selected && <div className="director-detail-grid"><div><small>Visit History</small><strong>{visitPlans.filter((item) => item.customerId === selected.id || item.customerName === selected.organizationName).length}</strong></div><div><small>Follow-ups</small><strong>{followUps.filter((item) => item.customerId === selected.id || item.customerName === selected.organizationName).length}</strong></div><div><small>Tenders</small><strong>{tenders.filter((item) => item.customerId === selected.id).length}</strong></div><div><small>Comments</small><strong>{directorComments.filter((item) => item.referenceId === selected.id).length}</strong></div><div><small>Address</small><strong>{selected.address || 'Not provided'}</strong></div><div><small>Tender Related</small><strong>{selected.isTenderRelated ? 'Yes' : 'No'}</strong></div></div>}</Modal><Modal open={Boolean(commentTarget)} onClose={() => setCommentTarget(null)} title="Add Customer Comment" footer={<><Button variant="secondary" onClick={() => setCommentTarget(null)}>Cancel</Button><Button onClick={postComment} disabled={!comment.trim() || !commentTarget?.createdBy}>Send Comment</Button></>}><TextArea label="Director Comment" required value={comment} onChange={(event) => setComment(event.target.value)} />{!commentTarget?.createdBy && <p className="ds-field__error">The customer record has no Marketing owner to notify.</p>}</Modal></div>;
};
export default CustomersOverview;
