import React, { useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Bell, Calendar, Clock, Download, FileText, MapPin, Package, Phone, Printer, Search } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Badge, Button, DataTable, EmptyState, FormField, Modal, PageHeader, SectionCard, SelectField, TextArea } from '../ui';
import { normalizePlanStatus } from '../../utils/planStatus';
import { AnalyticsTabs } from './AnalyticsTabs';
import { CompanyLogo } from '../common/CompanyLogo';

const today = () => new Date().toISOString().slice(0, 10);
const text = (value) => value || 'Not provided';
const productText = (row) => Array.isArray(row.products) ? row.products.join(', ') : (row.products || row.requirement || 'Not provided');
const destinationText = (row) => row.customerName || row.organizationName || 'Organization not provided';
const statusTone = (status) => ['Submitted', 'Completed', 'Approved', 'Won'].includes(normalizePlanStatus(status)) ? 'success' : ['Cancelled', 'Rejected', 'Lost', 'Overdue'].includes(normalizePlanStatus(status)) ? 'danger' : ['Pending', 'Changes Requested'].includes(normalizePlanStatus(status)) ? 'warning' : 'neutral';

export const DirectorOperations = () => {
  const location = useLocation();
  const { currentUser, users, products, visitPlans, visitReports, dailyReports, followUps, tenders, notifications, addDirectorComment, showToast } = useApp();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('All');
  const [employeeFilter, setEmployeeFilter] = useState('All');
  const [dateFilter, setDateFilter] = useState('');
  const [areaFilter, setAreaFilter] = useState('');
  const [selected, setSelected] = useState(null);
  const [commentTarget, setCommentTarget] = useState(null);
  const [comment, setComment] = useState('');
  const marketing = users.filter((user) => ['Marketing', 'Marketing Team'].includes(user.role));
  const employeeName = (employeeId, fallback) => fallback || marketing.find((user) => user.employeeId === employeeId)?.fullName || marketing.find((user) => user.employeeId === employeeId)?.username || employeeId || 'Not provided';
  const employeeMobile = (employeeId) => marketing.find((user) => user.employeeId === employeeId)?.mobileNumber || marketing.find((user) => user.employeeId === employeeId)?.mobile;
  const matches = (row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase());
  const addComment = async () => { if (!commentTarget || !comment.trim()) return; await addDirectorComment({ targetEmployeeId: commentTarget.employeeId || commentTarget.createdBy || commentTarget.assignedEmployeeId, targetEmployeeName: employeeName(commentTarget.employeeId || commentTarget.createdBy || commentTarget.assignedEmployeeId, commentTarget.fullName), targetModule: commentTarget.module, referenceId: String(commentTarget.id), message: comment.trim() }); setComment(''); setCommentTarget(null); };
  const commentButton = (row, module) => <Button variant="secondary" onClick={() => setCommentTarget({ ...row, module })}>Comment</Button>;
  const detailModal = <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.title || 'Details'} footer={<><Button variant="secondary" onClick={() => setSelected(null)}>Close</Button>{selected?.employeePhone && <Button onClick={() => { window.location.href = `tel:${selected.employeePhone}`; }}><Phone size={16} /> Call Employee</Button>}</>}>{selected && <div className="director-detail-grid">{Object.entries(selected.details).map(([label, value]) => <div key={label}><small>{label}</small><strong>{Array.isArray(value) ? value.join(', ') : text(value)}</strong></div>)}</div>}</Modal>;
  const commentModal = <Modal open={Boolean(commentTarget)} onClose={() => setCommentTarget(null)} title="Add Director Comment" subtitle={commentTarget?.module} footer={<><Button variant="secondary" onClick={() => setCommentTarget(null)}>Cancel</Button><Button onClick={addComment} disabled={!comment.trim()}>Send Comment</Button></>}><TextArea label="Comment" required value={comment} onChange={(event) => setComment(event.target.value)} /></Modal>;

  const filterBar = <div className="director-filter-bar"><div className="director-search"><Search size={17} /><FormField label="Search" value={search} onChange={(event) => setSearch(event.target.value)} /></div><SelectField label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Submitted</option><option>Planned</option><option>Started</option><option>Completed</option><option>Cancelled</option><option>Changes Requested</option></SelectField></div>;

  if (location.pathname === '/director/today-schedule') {
    const rows = visitPlans.filter((row) => row.visitDate === today()).filter(matches).filter((row) => status === 'All' || normalizePlanStatus(row.status) === status);
    const columns = [
      { key: 'employee', label: 'Employee', render: (row) => <><strong>{employeeName(row.employeeId, row.employeeName || row.fullName)}</strong><small>{text(row.employeeId)}</small></> }, { key: 'date', label: 'Visit Date', render: (row) => text(row.visitDate) }, { key: 'time', label: 'Expected Time', render: (row) => text(row.expectedTime) }, { key: 'area', label: 'Area / City', render: (row) => row.area || row.city || row.district || 'Not provided' }, { key: 'customer', label: 'Customer / Organization', render: destinationText }, { key: 'purpose', label: 'Visit Purpose', render: (row) => text(row.visitPurpose) }, { key: 'product', label: 'Products', render: productText }, { key: 'requirement', label: 'Requirement', render: (row) => text(row.requirement) }, { key: 'priority', label: 'Priority', render: (row) => text(row.priority) }, { key: 'notes', label: 'Notes', render: (row) => text(row.notes) }, { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{normalizePlanStatus(row.status)}</Badge> }, { key: 'actions', label: 'Details', render: (row) => <Button variant="secondary" onClick={() => setSelected({ title: 'Visit Plan Details', employeePhone: employeeMobile(row.employeeId), details: { 'Employee Name': employeeName(row.employeeId, row.employeeName || row.fullName), 'Employee ID': row.employeeId, 'Visit Date': row.visitDate, Time: row.expectedTime, 'Area / City': row.area || row.city || row.district, 'Customer / Organization': destinationText(row), 'Contact Person': row.contactPerson, 'Mobile Number': row.mobileNumber, Purpose: row.visitPurpose, Products: row.products, Requirement: row.requirement, Priority: row.priority, Notes: row.notes, 'Current Status': normalizePlanStatus(row.status), 'Submitted Date and Time': row.submittedAt ? new Date(row.submittedAt).toLocaleString() : null } })}>View Details</Button> }
    ];
    return <div className="ds-page"><PageHeader title="Today’s Team Schedule" description="Read-only live status for every Marketing employee’s visits today." />{filterBar}<DataTable rows={rows} columns={columns} empty={<EmptyState icon={Calendar} title="No team visits scheduled today" description="Today’s submitted visit plans will appear here." />} />{detailModal}</div>;
  }

  if (location.pathname === '/director/visit-plans') {
    const rows = visitPlans
      .filter(matches)
      .filter((row) => employeeFilter === 'All' || row.employeeId === employeeFilter)
      .filter((row) => !dateFilter || row.visitDate === dateFilter)
      .filter((row) => !areaFilter || String(row.area || row.city || row.district || '').toLowerCase().includes(areaFilter.toLowerCase()))
      .filter((row) => status === 'All' || normalizePlanStatus(row.status) === status);
    const visitFilterBar = <div className="director-filter-bar"><div className="director-search"><Search size={17} /><FormField label="Search" value={search} onChange={(event) => setSearch(event.target.value)} /></div><SelectField label="Employee" value={employeeFilter} onChange={(event) => setEmployeeFilter(event.target.value)}><option>All</option>{marketing.map((employee) => <option key={employee.id} value={employee.employeeId}>{employee.fullName || employee.username || employee.employeeId}</option>)}</SelectField><FormField label="Date" type="date" value={dateFilter} onChange={(event) => setDateFilter(event.target.value)} /><FormField label="Area" value={areaFilter} onChange={(event) => setAreaFilter(event.target.value)} /><SelectField label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>Submitted</option><option>Draft</option><option>Planned</option><option>Started</option><option>Completed</option><option>Cancelled</option></SelectField></div>;
    const columns = [{ key: 'employee', label: 'Employee', render: (row) => <><strong>{employeeName(row.employeeId, row.employeeName || row.fullName)}</strong><small>{text(row.employeeId)}</small></> }, { key: 'date', label: 'Visit Date', render: (row) => text(row.visitDate) }, { key: 'time', label: 'Expected Time', render: (row) => text(row.expectedTime) }, { key: 'area', label: 'Area / City', render: (row) => row.area || row.city || row.district || 'Not provided' }, { key: 'customer', label: 'Customer / Organization', render: (row) => row.customerName || row.organizationName || 'Customer not selected' }, { key: 'purpose', label: 'Visit Purpose', render: (row) => text(row.visitPurpose) }, { key: 'products', label: 'Products', render: productText }, { key: 'requirement', label: 'Requirement', render: (row) => text(row.requirement) }, { key: 'priority', label: 'Priority', render: (row) => text(row.priority) }, { key: 'notes', label: 'Notes', render: (row) => text(row.notes) }, { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{normalizePlanStatus(row.status)}</Badge> }, { key: 'actions', label: 'Details', render: (row) => <Button variant="secondary" onClick={() => setSelected({ title: 'Visit Plan Details', employeePhone: employeeMobile(row.employeeId), details: { 'Employee Name': employeeName(row.employeeId, row.employeeName || row.fullName), 'Employee ID': row.employeeId, 'Visit Date': row.visitDate, Time: row.expectedTime, 'Area / City': row.area || row.city || row.district, 'Customer / Organization': row.customerName || row.organizationName || 'Customer not selected', 'Contact Person': row.contactPerson, 'Mobile Number': row.mobileNumber, Purpose: row.visitPurpose, Products: row.products, Requirement: row.requirement, Priority: row.priority, Notes: row.notes, 'Current Status': normalizePlanStatus(row.status), 'Submitted Date and Time': row.submittedAt ? new Date(row.submittedAt).toLocaleString() : null } })}>View Details</Button> }];
    return <div className="ds-page"><PageHeader title="Visit Plans" description="View individual Marketing visit plans and complete destination details." />{visitFilterBar}<DataTable rows={rows} columns={columns} empty={<EmptyState icon={Calendar} title="No visit plans found" />} />{detailModal}</div>;
  }

  if (location.pathname === '/director/daily-reports') {
    const rows = dailyReports.filter(matches).filter((row) => status === 'All' || row.status === status);
    const columns = [{ key: 'employee', label: 'Employee', render: (row) => employeeName(row.employeeId, row.fullName || row.employeeName) }, { key: 'date', label: 'Date', render: (row) => row.date || row.reportDate }, { key: 'planned', label: 'Planned Visits', render: (row) => row.plannedVisits ?? 0 }, { key: 'completed', label: 'Completed', render: (row) => row.completedVisits ?? 0 }, { key: 'cancelled', label: 'Cancelled', render: (row) => row.cancelledVisits ?? 0 }, { key: 'pending', label: 'Pending Actions', render: (row) => row.pendingActions ?? 0 }, { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{text(row.status)}</Badge> }, { key: 'actions', label: 'Actions', render: (row) => <div className="ds-page-actions"><Button variant="secondary" onClick={() => setSelected({ title: 'Daily Report', details: row })}>View</Button>{commentButton(row, 'Daily Report')}</div> }];
    return <div className="ds-page"><PageHeader title="Daily Reports" description="Review submitted daily summaries. Locking, reopening, editing, and deletion remain Admin-only." />{filterBar}<DataTable rows={rows} columns={columns} empty={<EmptyState icon={FileText} title="No daily reports found" />} />{detailModal}{commentModal}</div>;
  }

  if (location.pathname === '/director/follow-ups') {
    const rows = followUps.filter(matches).filter((row) => status === 'All' || row.status === status);
    const columns = [{ key: 'employee', label: 'Employee', render: (row) => employeeName(row.employeeId, row.fullName || row.employeeName) }, { key: 'customer', label: 'Organization / Person', render: (row) => text(row.customerName) }, { key: 'date', label: 'Follow-up Date', render: (row) => row.followUpDate }, { key: 'type', label: 'Type', render: (row) => text(row.followUpType || row.type) }, { key: 'purpose', label: 'Purpose', render: (row) => text(row.purpose) }, { key: 'priority', label: 'Priority', render: (row) => text(row.priority) }, { key: 'status', label: 'Status', render: (row) => <Badge tone={statusTone(row.status)}>{text(row.status)}</Badge> }, { key: 'actions', label: 'Actions', render: (row) => <div className="ds-page-actions"><Button variant="secondary" onClick={() => setSelected({ title: 'Follow-up Details', details: row })}>View</Button>{commentButton(row, 'Follow-up')}</div> }];
    return <div className="ds-page"><PageHeader title="Follow-up Monitoring" description="Monitor today, upcoming, overdue, and completed Marketing follow-ups." />{filterBar}<DataTable rows={rows} columns={columns} empty={<EmptyState icon={Clock} title="No follow-ups found" />} />{detailModal}{commentModal}</div>;
  }

  if (location.pathname === '/director/analytics/products') {
    const rows = products.map((product) => { const visits = visitPlans.filter((plan) => (plan.products || []).includes(product.name)); return { id: product.id, name: product.name, visits: visits.length, requirements: visits.filter((plan) => plan.requirement).length, demos: visits.filter((plan) => /demo/i.test(plan.visitPurpose || '')).length, quotations: visitReports.filter((report) => report.isQuotationRequired && (report.interestedProducts || []).includes(product.name)).length, tenders: tenders.filter((tender) => (tender.requiredProducts || []).includes(product.name)).length, followups: followUps.filter((followUp) => String(followUp.notes || followUp.purpose || '').includes(product.name) && followUp.status === 'Pending').length }; }).filter(matches);
    const columns = [{ key: 'name', label: 'Product' }, { key: 'visits', label: 'Total Visits' }, { key: 'requirements', label: 'New Requirements' }, { key: 'demos', label: 'Demo Requests' }, { key: 'quotations', label: 'Quotation Requests' }, { key: 'tenders', label: 'Tender Opportunities' }, { key: 'followups', label: 'Pending Follow-ups' }];
    return <div className="ds-page"><PageHeader title="Analytics" description="Product-wise Marketing demand and opportunity indicators." /><AnalyticsTabs />{filterBar}<DataTable rows={rows} columns={columns} empty={<EmptyState icon={Package} title="No product activity found" />} /></div>;
  }

  if (location.pathname === '/director/analytics/areas') {
    const areas = [...new Set([...visitPlans.map((row) => row.area || row.city || row.district), ...tenders.map((row) => row.area)].filter(Boolean))];
    const rows = areas.map((area) => ({ id: area, area, state: 'Tamil Nadu', visits: visitPlans.filter((row) => [row.area, row.city, row.district].includes(area)).length, requirements: visitPlans.filter((row) => [row.area, row.city, row.district].includes(area) && row.requirement).length, tenders: tenders.filter((row) => row.area === area).length })).filter(matches);
    return <div className="ds-page"><PageHeader title="Analytics" description="Area-wise visits, requirements, and tender opportunities." /><AnalyticsTabs />{filterBar}<DataTable rows={rows} columns={[{ key: 'area', label: 'District / City / Area' }, { key: 'state', label: 'State' }, { key: 'visits', label: 'Visits' }, { key: 'requirements', label: 'Requirements' }, { key: 'tenders', label: 'Tenders' }]} empty={<EmptyState icon={MapPin} title="No area activity found" />} /></div>;
  }

  if (location.pathname === '/director/reports') {
    const rows = visitPlans.filter(matches).map((row) => ({ id: row.id, employee: employeeName(row.employeeId, row.fullName), date: row.visitDate, area: row.area || row.city || row.district, customer: row.customerName, products: productText(row), status: normalizePlanStatus(row.status) }));
    const downloadCsv = () => { const header = ['Employee', 'Date', 'Area', 'Organization', 'Products', 'Status']; const csv = [header, ...rows.map((row) => [row.employee, row.date, row.area, row.customer, row.products, row.status])].map((values) => values.map((value) => `"${String(value || '').replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'director-team-report.csv'; link.click(); URL.revokeObjectURL(url); showToast('Report exported successfully.', 'success'); };
    return <div className="ds-page"><div className="report-brand"><CompanyLogo /><span>Whale Enterprise</span></div><PageHeader title="Director Reports" description="Team, employee, area, product, organization, follow-up, tender, and visit reporting." actions={<><Button variant="secondary" onClick={downloadCsv}><Download size={16} /> Excel / CSV</Button><Button variant="secondary" onClick={() => window.print()}><Printer size={16} /> PDF / Print</Button></>} />{filterBar}<DataTable rows={rows} columns={[{ key: 'employee', label: 'Employee' }, { key: 'date', label: 'Date' }, { key: 'area', label: 'Area' }, { key: 'customer', label: 'Organization' }, { key: 'products', label: 'Products' }, { key: 'status', label: 'Status' }]} empty={<EmptyState icon={FileText} title="No report data found" />} /></div>;
  }

  const rows = notifications.filter((notification) => !notification.userId || notification.userId === currentUser?.employeeId).filter(matches);
  return <div className="ds-page"><PageHeader title="Notifications" description="View plan, visit, report, tender, follow-up, and Admin updates." actions={<Badge tone="warning">{rows.filter((row) => !row.isRead).length} unread</Badge>} /><SectionCard><DataTable rows={rows} columns={[{ key: 'title', label: 'Notification', render: (row) => <><strong>{text(row.title)}</strong><small>{text(row.message)}</small></> }, { key: 'type', label: 'Type', render: (row) => text(row.type) }, { key: 'time', label: 'Time', render: (row) => row.timestamp || row.createdAt }, { key: 'status', label: 'Status', render: (row) => <Badge tone={row.isRead ? 'neutral' : 'warning'}>{row.isRead ? 'Read' : 'Unread'}</Badge> }, { key: 'action', label: 'Details', render: (row) => <Button variant="secondary" onClick={() => setSelected({ title: row.title || 'Notification Details', details: { Message: row.message, Type: row.type, Time: row.timestamp || row.createdAt, Status: row.isRead ? 'Read' : 'Unread' } })}>View Details</Button> }]} empty={<EmptyState icon={Bell} title="No notifications" />} /></SectionCard>{detailModal}</div>;
};

export default DirectorOperations;
