import React, { useMemo, useState } from 'react';
import { Download, FileText, Search } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Badge, Button, DataTable, EmptyState, FormField, Modal, PageHeader, SelectField, TextArea } from '../ui';

const daysUntil = (date) => date ? Math.ceil((new Date(date) - new Date()) / 86400000) : null;
export const TenderMonitoring = () => {
  const { tenders, addDirectorComment, refreshEntity, lastUpdated } = useApp(); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [selected, setSelected] = useState(null); const [commentTarget, setCommentTarget] = useState(null); const [comment, setComment] = useState('');
  const rows = useMemo(() => tenders.filter((item) => status === 'All' || item.status === status).filter((item) => `${item.tenderName || ''} ${item.tenderNumber || ''} ${item.department || ''}`.toLowerCase().includes(search.toLowerCase())), [search, status, tenders]);
  const statuses = ['New Enquiry', 'Preparing', 'Submitted', 'Technical Evaluation', 'Financial Evaluation', 'Won', 'Lost'];
  const postComment = async () => { if (!comment.trim()) return; await addDirectorComment({ targetEmployeeId: commentTarget.assignedEmployeeId, targetEmployeeName: commentTarget.assignedEmployeeName || commentTarget.assignedEmployeeId, targetModule: 'Tender', referenceId: commentTarget.id, message: comment.trim() }); setComment(''); setCommentTarget(null); };
  const columns = [{ key: 'name', label: 'Tender', render: (row) => <><strong>{row.tenderName || 'Not provided'}</strong><small>{row.tenderNumber || 'Not provided'}</small></> }, { key: 'department', label: 'Department' }, { key: 'closingDate', label: 'Closing Date', render: (row) => { const days = daysUntil(row.closingDate); return <>{row.closingDate || 'Not provided'}{days !== null && days <= 3 && <Badge tone="danger">{days < 0 ? 'Overdue' : days === 0 ? 'Closing Today' : `Closing in ${days} Days`}</Badge>}</>; } }, { key: 'products', label: 'Products', render: (row) => (row.requiredProducts || row.products || []).join?.(', ') || row.requiredProducts || 'Not provided' }, { key: 'value', label: 'Value', render: (row) => row.tenderValue || 'Not provided' }, { key: 'employee', label: 'Assigned Employee', render: (row) => row.assignedEmployeeName || row.assignedEmployeeId || 'Not provided' }, { key: 'status', label: 'Status', render: (row) => <Badge>{row.status || 'New Enquiry'}</Badge> }, { key: 'action', label: 'Actions', render: (row) => <div className="ds-page-actions"><Button variant="secondary" onClick={() => setSelected(row)}>View</Button><Button variant="secondary" onClick={() => setCommentTarget(row)}>Comment</Button></div> }];
  return <div className="ds-page"><PageHeader title="Tender Monitoring" description={`Monitor tender deadlines and team ownership. Last updated ${lastUpdated ? lastUpdated.toLocaleTimeString() : 'Not available'}.`} /><div className="director-kpi-grid">{statuses.map((item) => <div key={item}><small>{item}</small><strong>{tenders.filter((tender) => tender.status === item).length}</strong></div>)}<div><small>Closing Soon</small><strong>{tenders.filter((tender) => { const days = daysUntil(tender.closingDate); return days !== null && days >= 0 && days <= 3; }).length}</strong></div></div><div className="director-filter-bar"><div className="director-search"><Search size={17} /><FormField label="Search tenders" value={search} onChange={(event) => setSearch(event.target.value)} /></div><SelectField label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}</SelectField></div><DataTable rows={rows} columns={columns} empty={<EmptyState icon={FileText} title="No active tenders found" description="Clear filters or refresh tender data." action={<Button onClick={() => refreshEntity('tenders')}>Refresh</Button>} />} /><Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.tenderName || 'Tender Details'} subtitle={selected?.tenderNumber || 'No reference provided'} footer={<><Button variant="secondary" onClick={() => setSelected(null)}>Close</Button>{selected?.documents?.[0] && <Button onClick={() => window.open(selected.documents[0], '_blank', 'noopener,noreferrer')}><Download size={16} /> Download Documents</Button>}</>}>{selected && <div className="director-detail-grid"><div><small>Department</small><strong>{selected.department || 'Not provided'}</strong></div><div><small>Area</small><strong>{selected.area || 'Not provided'}</strong></div><div><small>Closing Date</small><strong>{selected.closingDate || 'Not provided'}</strong></div><div><small>Value</small><strong>{selected.tenderValue || 'Not provided'}</strong></div><div><small>Priority</small><strong>{selected.priority || 'Normal'}</strong></div><div><small>Documents</small><strong>{selected.documents?.length || 0}</strong></div><div><small>Notes</small><strong>{selected.notes || 'Not provided'}</strong></div></div>}</Modal><Modal open={Boolean(commentTarget)} onClose={() => setCommentTarget(null)} title="Add Tender Comment" footer={<><Button variant="secondary" onClick={() => setCommentTarget(null)}>Cancel</Button><Button onClick={postComment} disabled={!comment.trim() || !commentTarget?.assignedEmployeeId}>Send Comment</Button></>}><TextArea label="Director Comment" required value={comment} onChange={(event) => setComment(event.target.value)} />{!commentTarget?.assignedEmployeeId && <p className="ds-field__error">This tender has no assigned Marketing employee to notify.</p>}</Modal></div>;
};
export default TenderMonitoring;
